CREATE DATABASE AirLinesBookingSystem;
USE AirLinesBookingSystem;

-- Creating all the dimension tables

CREATE TABLE AIRPORT(
	AIRPORTCODE CHAR(6) NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	LOCATION VARCHAR(50) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL
);
SELECT * FROM AIRPORT;

CREATE TABLE DATETIME(
	DATE date NOT NULL PRIMARY KEY,
	WEEKDAY VARCHAR(20),
	MONTH_NAME INT,
	YEAR INT
);

CREATE TABLE FLIGHTSERVICE(
	SERVICE_ID INT NOT NULL PRIMARY KEY,
	SERVICE CHAR(20) NOT NULL
);

CREATE TABLE DBO.FLIGHTCLASS(
	CLASS_ID INT NOT NULL PRIMARY KEY,
	CLASSNAME CHAR(20) NOT NULL
);

CREATE TABLE PASSENGERS(
	P_ID INT NOT NULL PRIMARY KEY,
	PNAME VARCHAR(30),
	AGE INT,
	GENDER VARCHAR(10)
);

CREATE TABLE PAYMENT(
	PAYMENTID INT NOT NULL PRIMARY KEY,
	AMOUNT INT
);


CREATE TABLE PAYMENTSTATUS(
	PAYMENTID INT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES PAYMENT(PAYMENTID),
	BOOKINGID INT,
	STATUS VARCHAR(10)

);



CREATE TABLE FLIGHT_DETAILS(
	FLIGHT_ID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR(20),
	SOURCE VARCHAR(20),
	SRC_AIRPORTCODE CHAR(6) NOT NULL FOREIGN KEY REFERENCES AIRPORT(AIRPORTCODE),
	DESTINATION VARCHAR(20),
	DST_AIRPORTCODE CHAR(6) NOT NULL FOREIGN KEY REFERENCES AIRPORT(AIRPORTCODE),
	D_DATETIME DATE FOREIGN KEY REFERENCES DATETIME(DATE),
	A_DATETIME DATE FOREIGN KEY REFERENCES DATETIME(DATE)
);


CREATE TABLE SEATS(
	SEAT_ID INT NOT NULL PRIMARY KEY,
	CLASS_ID INT FOREIGN KEY REFERENCES FLIGHTCLASS(CLASS_ID),
	SERVICE_ID INT FOREIGN KEY REFERENCES FLIGHTSERVICE(SERVICE_ID),
	FLIGHT_ID INT FOREIGN KEY REFERENCES FLIGHT_DETAILS(FLIGHT_ID)
)

CREATE TABLE FLIGHTCOST(
	FLIGHTID INT NOT NULL  FOREIGN KEY REFERENCES FLIGHT_DETAILS(FLIGHT_ID),
	SEATID INT NOT NULL  FOREIGN KEY REFERENCES SEATS(SEAT_ID),
	AMOUNT INT,
	CONSTRAINT PK_cost PRIMARY KEY (FLIGHTID,SEATID)
);

CREATE TABLE BOOKINGS(
	BOOKING_ID INT NOT NULL PRIMARY KEY,
	P_ID INT NOT NULL FOREIGN KEY REFERENCES PASSENGERS(P_ID),
	FLIGHT_ID INT NOT NULL FOREIGN KEY REFERENCES FLIGHT_DETAILS(FLIGHT_ID),
	SEAT_ID INT NOT NULL FOREIGN KEY REFERENCES SEATS(SEAT_ID),
	TRAVEL DATE FOREIGN KEY REFERENCES DATETIME(DATE),
	SRC VARCHAR(20),
	DEST VARCHAR(20)

);


ALTER TABLE PAYMENTSTATUS
ADD FOREIGN KEY (BOOKINGID) REFERENCES BOOKINGS(BOOKING_ID);

ALTER TABLE PASSENGERS
ADD EMAILID VARCHAR(30), MOBILENO INT